version: '3.8'

services:
  app:
    container_name: nest-shop-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=nest_shop
    depends_on:
      - postgres
    networks:
      - nest-shop-network

  postgres:
    container_name: nest-shop-postgres
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nest_shop
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nest-shop-network

networks:
  nest-shop-network:
    driver: bridge

volumes:
  postgres_data:
