name: GitHub Actions Demo 
run-name: ${{ github.actor }} тестирует GitHub Actions 🚀 
on: [push] 
jobs: 
  Explore-GitHub-Actions: 
    running-on: ubuntu-latest 
    steps: 
      - run: echo "🎉 Задание было автоматически запущено событием ${{ github.event_name }}." 
      - run: echo "🐧 Это задание теперь выполняется на сервере ${{ runner.os }}, размещенном на GitHub!" 
      - run: echo "🔎 Имя вашей ветки - ${{ github.ref }}, а ваш репозиторий - ${{ github.repository }}." 
      - name: Проверьте код репозитория 
        использует: actions/checkout@v4 
      - run: echo "💡 Репозиторий ${{ github.repository }} был клонирован в runner." 
      - run: echo "🖥️ Рабочий процесс теперь готов к тестированию вашего кода на бегуне." 
      - name: Список файлов в репозитории 
        run: | 
          ls ${{ github.workspace }} 
      - run: echo "🍏 Статус этой задачи ${{ job.status }}."
